#include "stm32g030xx.h"
#include "GPIO.h"

/*-------------------GPIO RCC CONFIGURE START-----------------*/

void GPIO_RCC_CONFIGURE(GPIO_X PORT)

{
	RCC ->IOPENR |= (1 << PORT);
}

/*-------------------GPIO RCC CONFIGURE END-----------------*/



/*-------------------GPIO CONFIGURE START-----------------*/

void GPIO_CONFIGURE(void)

{

/*------------------------ GPIO MODE SET ---------------------*/


	//---CLEAR ALL MODE
	
	GPIOA ->MODER &= ~(GPIO_MODER_MODE11);	

	GPIOA ->MODER &= ~(GPIO_MODER_MODE12);



	//---SET MODE AS ALTERNATE FUNCTION FOR I2C

	GPIOA ->MODER |= GPIO_MODER_MODE11_1;	

	GPIOA ->MODER |= GPIO_MODER_MODE12_1; 


	//---CLEAR BIT OPEN DRAIN PA11
	
	GPIOA->OTYPER &=~(GPIO_OTYPER_OT11); 
	
	//---CLEAR BIT OPEN DRAIN PA12

	GPIOA->OTYPER &=~(GPIO_OTYPER_OT12); 
	
	//---SET AS OPEN DRAIN PA11

	GPIOA->OTYPER |=GPIO_OTYPER_OT11;

	//---SET AS OPEN DRAIN PA12

	GPIOA->OTYPER |=GPIO_OTYPER_OT12;
	
	//---CLEAR BIT PULLUP PA11	
	
	GPIOA->PUPDR &=~(GPIO_PUPDR_PUPD11);

	//---CLEAR BIT PULLUP PA12	

	GPIOA->PUPDR &=~(GPIO_PUPDR_PUPD12); 
	
	//---SET AS PULLUP PA11
	
	GPIOA->PUPDR |=GPIO_PUPDR_PUPD11_0; 
	
	//---SET AS PULLUP PA12	

	GPIOA->PUPDR |=GPIO_PUPDR_PUPD12_0; 
	
	//---CLEAR BIT GPIO AS HIGH SPEED PA11

	GPIOA->OSPEEDR &=~(GPIO_OSPEEDR_OSPEED11); 
	
	//---CLEAR BIT GPIO AS HIGH SPEED PA12

	GPIOA->OSPEEDR &=~(GPIO_OSPEEDR_OSPEED12);

	//---SET GPIO AS HIGH SPEED PA11

	GPIOA->OSPEEDR |=GPIO_OSPEEDR_OSPEED11_1; 
	
	//---SET GPIO AS HIGH SPEED PA12

	GPIOA->OSPEEDR |=GPIO_OSPEEDR_OSPEED12_1; 
	
	//---CLEAR BIT GPIO ALTERNATE PA11

	GPIOA->AFR[1] &= ~GPIO_AFRH_AFSEL11; 
	
	//---CLEAR BIT GPIO ALTERNATE PA12

	GPIOA->AFR[1] &= ~GPIO_AFRH_AFSEL12; 
	
	//---SET GPIO ALTERNATE PA11

	GPIOA->AFR[1] |= (6 << 12);

	//---SET GPIO ALTERNATE PA12

	GPIOA->AFR[1] |= (6 << 16); 
	

}

/*-------------------GPIO CONFIGURE END-----------------*/






