#include "stm32g030xx.h"
#include "I2C_2.h"
#include "SSD1306.h"

void OLED_FUN_CMD(OLED_FUN_CMD_X FUN_CMD_X)
{
	I2C2_WRITE_CMD(FUN_CMD_X);
}

void OLED_ADDRESSING_CMD(OLED_ADDRESSING_CMD_X ADDR_CMD_X)

{
	I2C2_WRITE_CMD(ADDR_CMD_X);
}

void OLED_ADDRESSING_CMD_DATA(OLED_ADDRESSING_CMD_DATA_X ADDR_DATA_X)
{
	I2C2_WRITE_CMD(ADDR_DATA_X);
}


void OLED_STARTING_PAGE(OLED_PAGE_X PAGE_X)
{
	I2C2_WRITE_CMD(PAGE_X);
}



void OLED_SET_COLUMN();