#include "stm32g030xx.h"
#include "I2C_2.h"
#include "SSD1306.h"


//OLED INIT
void OLED_COMMAND(OLED_CMD_X OLED_CMD)
{
	I2C2_WRITE_CMD(OLED_CMD);
	
}
void OLED_INIT()
{
	OLED_COMMAND(SET_DISPLAY_OFF);
	OLED_COMMAND(SET_CHARGE_PUMP_SETTING);
	OLED_COMMAND(SET_CHARGE_PUMP_ENABLE);
	
	//OLED_COMMAND(SET_ENTIRE_DISPLAY_ON);
	//OLED_COMMAND(SET_DISPLAY_ON);
	
	
}


