/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'OLED_Display' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Device:Startup@1.4.2 */
#define RTE_DEVICE_STARTUP_STM32G0XX    /* Device Startup for STM32G0 */


#endif /* RTE_COMPONENTS_H */
